WebApplication3/Models/Kullanici.cs
using System.Collections.Generic;

namespace WebApplication3.Models
{
    public class Kullanici
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string TcNo { get; set; }
        public string Email { get; set; }
        public string Sifre { get; set; }
        public int RolId { get; set; }

        public Rol Rol { get; set; }

    }
}

WebApplication3/Controllers/KullaniciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication3.Controllers
{
   
    public class KullaniciController : Controller
    {
        Models.Context db = new Models.Context();
        //CRUD Create,Read,Update,Delete
        // GET: Kullanici
        [Authorize(Roles = "Yönetici")]
        public ActionResult Index()
        {
            
            return View(db.Kullanici.Include("Rol").ToList());
        }
        public ActionResult Create()
        {
            var rolList = db.Rol.ToList();
            ViewData["Rol"] = rolList;

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int rolId, string Tc, string Ad, string Soyad, string Email,string Sifre)
        {
            Models.Kullanici _kullanici = new Models.Kullanici();
            _kullanici.Ad = Ad;
            _kullanici.Soyad = Soyad;
            _kullanici.TcNo = Tc;
            _kullanici.Email = Email;
            _kullanici.Sifre = Sifre;
            _kullanici.RolId = rolId;
            db.Kullanici.Add(_kullanici);
            db.SaveChanges();
            return RedirectToAction("Index","Giris");
        }
        
        public ActionResult Update(int Id)
        {
            var kullanici = db.Kullanici.Single(x => x.Id == Id);
            return View(kullanici);

        }
        [HttpPost]
        public ActionResult Update(Models.Kullanici kullanici)
        {
            var _kullanici = db.Kullanici.Single(x => x.Id == kullanici.Id);
            _kullanici.Ad = kullanici.Ad;
            _kullanici.Soyad = kullanici.Soyad;
            _kullanici.TcNo = kullanici.TcNo;            
            _kullanici.Email = kullanici.Email;
            _kullanici.Sifre = kullanici.Sifre;           

            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int Id)
        {
            db.Kullanici.Remove(db.Kullanici.Single(x => x.Id == Id));
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebApplication3/Views/Kullanici/Create.cshtml
@*@model WebApplication3.Models.Kullanici*@
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var rolList = ViewData["Rol"] as List<WebApplication3.Models.Rol>;
}
<h2>Yeni Kullanici</h2>
@using (Html.BeginForm("Create", "Kullanici", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label for="Ad">Ad</label>
        <input class="form-control" name="Ad" />
        @*@Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })*@
    </div>
    <div class="form-group">
        <label for="Soyad">Soyad</label>
        <input class="form-control" name="Soyad" />
        @*  @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control" })*@
    </div>
    <div class="form-group">
        <label for="TcNo">TC NO</label>
        <input class="form-control" name="Tc" />
        @* @Html.TextBoxFor(x => x.TcNo, new { @class = "form-control" })*@
    </div>
    <div class="form-group">
        <label for="Email">Email</label>
        <input class="form-control" name="Email" />
        @* @Html.TextBoxFor(x => x.Email, new { @class = "form-control", @type = "form-control" })*@
    </div>
    <div class="form-group">
        <label for="Sifre">Sifre</label>
        <input class="form-control" name="Sifre" />
        @* @Html.TextBoxFor(x => x.Sifre, new { @class = "form-control", @type = "form-control" })*@
    </div>
    <div class="form-group">
        <label for="RolId">RolId</label>
        @Html.DropDownList("RolId", new SelectList(rolList.ToList(), "Id", "Ad"), "Rolünüzü Seçiniz", new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Ekle</button>
}

WebApplication3/Views/Kullanici/Delete.cshtml
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

WebApplication3/Views/Kullanici/Index.cshtml
@model IEnumerable<WebApplication3.Models.Kullanici>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Ad</th>
            <th scope="col">Soyad</th>
            <th scope="col">TC</th>
            <th scope="col">Email</th>
            <th scope="col">Sifre</th>
            <th scope="col">RolAd</th>
            <th>
                <a href="@Url.Action("Create","Kullanici")" class="btn btn-primary">Yeni</a>
                @* <button type="button" class="btn btn-primary">Yeni</button>*@
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ToList())
        {
        <tr>
            <th scope="row">@item.Id</th>
            <td>@item.Ad</td>
            <td>@item.Soyad</td>
            <td>@item.TcNo</td>
            <td>@item.Email</td>
            <td>@item.Sifre</td>
            <th scope="row">@item.Rol.Ad</th>

            <td>
                <a href="@Url.Action("Update","Kullanici",new { @Id = item.Id})" class="btn btn-danger">Düzenle</a>
                <a href="@Url.Action("Delete","Kullanici",new { @Id = item.Id})" class="btn btn-danger">Sil</a>
            </td>

        </tr>
        }
    </tbody>
</table>

WebApplication3/Views/Kullanici/Update.cshtml
@model WebApplication3.Models.Kullanici
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Yeni Kullanici</h2>

@using (Html.BeginForm("Update", "Kullanici", FormMethod.Post))
{

    <div class="form-group">
        <label for="exampleInputEmail1">Id</label>
        @Html.TextBoxFor(x => x.Id, new { @class = "form-control", @readonly = "@readonly" })
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Kullanici Ad</label>
        @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Kullanici Soyad</label>
        @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Kullanici Tc NO</label>
        @Html.TextBoxFor(x => x.TcNo, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Kullanici Email</label>
        @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Kullanici Sifre</label>
        @Html.TextBoxFor(x => x.Sifre, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Düzenle</button>
}