WebApplication3/Controllers/DurumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication3.Controllers
{
    public class DurumController : Controller
    {
        Models.Context db = new Models.Context();
        // GET: Durum
        public ActionResult Index()
        {
            return View(db.Durum.ToList());
        }
        [Authorize(Roles = "Yönetici,Başkan")]
        public ActionResult Creat()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Creat(Models.Durum durum)
        {
            Models.Durum _durum = new Models.Durum();
            _durum.Ad = durum.Ad;
            db.Durum.Add(_durum);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Update(int Id)
        {
            var durum = db.Durum.Single(y => y.Id == Id);
            return View(durum);
        }
        [HttpPost]
        public ActionResult Update(Models.Durum durum)
        {
            var _durum = db.Durum.Single(y => y.Id == durum.Id);
            _durum.Ad = durum.Ad;
            db.SaveChanges();
            return RedirectToAction("Index");
           
        }
        public ActionResult Delete(int Id)
        {
            db.Durum.Remove(db.Durum.Single(x => x.Id == Id));
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebApplication3/Controllers/KargoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication3.Controllers
{
    public class KargoController : Controller
    {
        // GET: Kargo
        Models.Context db = new Models.Context();
        
        public ActionResult Index()
        {
            return View(db.Kargo.Include("Kargocu").Include("Urun").Include("Durum").ToList());
        }
        [Authorize(Roles = "Yönetici,Başkan")]
        public ActionResult Creat()
        {
            
            var kargocuList = db.Kargocu.ToList();
            ViewData["Kargocu"] = kargocuList;
            
            var UrunList = db.Urun.ToList();
            ViewData["Urun"] = UrunList;
            
            var DurumList = db.Durum.ToList();
            ViewData["Durum"] = DurumList;
           
            return View();
           
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int KargocuId, int UrunId, int DurumID)
        {
            //asdasd
            Models.Kargo _kargo = new Models.Kargo();
            _kargo.SonIslemTarihi = DateTime.Now;
            _kargo.KargocuId =KargocuId ;
            _kargo.UrunId = UrunId;
            _kargo.DurumID = DurumID;           
            db.Kargo.Add(_kargo);
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult Update(int Id)
        {
            var kargo = db.Kargo.Single(x => x.Id == Id);
            var kargocuList = db.Kargocu.ToList();
            ViewData["Kargocu"] = kargocuList;

            var UrunList = db.Urun.ToList();
            ViewData["Urun"] = UrunList;

            var DurumList = db.Durum.ToList();
            ViewData["Durum"] = DurumList;

            
            return View(kargo);
        }
        [HttpPost]
        public ActionResult Update(Models.Kargo kargo)
        {
            var _kargo = db.Kargo.Single(x => x.Id == kargo.Id);
            _kargo.KargocuId = kargo.KargocuId;
            _kargo.UrunId = kargo.UrunId;
            _kargo.DurumID = kargo.DurumID;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int Id)
        {
            db.Kargo.Remove(db.Kargo.Single(x => x.Id == Id));
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebApplication3/Controllers/RolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication3.Controllers
{
    public class RolController : Controller
    {
        Models.Context db = new Models.Context();

        // GET: Rol
        [Authorize(Roles = "Yönetici,Başkan")]
        public ActionResult Index()
        {
            return View(db.Rol.ToList());
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Models.Rol rol)
        {
            Models.Rol _rol = new Models.Rol();
            _rol.Ad = rol.Ad;
            db.Rol.Add(_rol);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Update(int Id)
        {
            var rol = db.Rol.Single(y => y.Id == Id);
            return View(rol);
        }
        [HttpPost]
        public ActionResult Update(Models.Rol rol)
        {
            var _rol = db.Rol.Single(y => y.Id == rol.Id);
            _rol.Ad = rol.Ad;
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult Delete(int Id)
        {
            db.Rol.Remove(db.Rol.Single(x => x.Id == Id));
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}  
     

WebApplication3/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication3.Controllers
{
    public class UrunController : Controller
    {
        // GET: Urun
        Models.Context db = new Models.Context();
        public ActionResult Index()
        {
            return View(db.Urun.ToList());
        }
        public ActionResult Creat()
        {
            return View();  
        }
        [HttpPost]
        
        public ActionResult Creat(Models.Urun urun)
        {

            Models.Urun _urun = new Models.Urun();

            _urun.Ad = urun.Ad;
            db.Urun.Add(_urun);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Update(int Id)
        {
            var urun = db.Urun.Single(x => x.Id == Id);
            return View(urun);
        }
        [HttpPost]
        public ActionResult Update(Models.Urun urun)
        {
            var _urun = db.Urun.Single(x => x.Id == urun.Id);
            _urun.Ad = urun.Ad;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int Id)
        {
            db.Urun.Remove(db.Urun.Single(x => x.Id == Id));
            db.SaveChanges();
            return RedirectToAction("Index");
            
        }

    }
}

WebApplication3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Anasayfa", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <a href="@Url.Action("Index","Kullanici")" class="navbar-brand">Kullanici</a>
                <a href="@Url.Action("Index","Rol")" class="navbar-brand">Rol</a>
                <a href="@Url.Action("Index","Kargo")" class="navbar-brand">Kargo</a>
                <a href="@Url.Action("Index","Kargocu")" class="navbar-brand">Kargocu</a>
                <a href="@Url.Action("Index","KargoSirketi")" class="navbar-brand">KargoSirketi</a>
                <a href="@Url.Action("Index","Durum")" class="navbar-brand">Durum</a>
                <a href="@Url.Action("Index","Urun")" class="navbar-brand">Ürün</a>
            </div>
            @Html.ActionLink("Çıkış", "Cikis", "Giris")


        </div>
    </div>
            @*<div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </div>*@
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ☠⇝√〠£</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>