WebApplication3/Models/Kargocu.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication3.Models
{
    public class Kargocu
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string TcNo { get; set; }
        public string TelNo { get; set; }
        public int KargoSirketiId { get; set; }
        public KargoSirketi KargoSirketi { get; set; }
        public ICollection<Kargo> Kargo { get; set; }
    }
}

WebApplication3/Controllers/KargocuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication3.Controllers
{
    [Authorize]
    public class KargocuController : Controller
    {
       
        // GET: Kargocu
        Models.Context db = new Models.Context();
        [Authorize(Roles = "Yönetici,Başkan")]
        public ActionResult Index()
        {
            
            var a = this.Session.SessionID;
            
                return View(db.Kargocu.ToList());

            
        }
         
        public ActionResult Create()
        {
            var kargoSirketiList = db.KargoSirketi.ToList();
            ViewData["KargoSirketi"] = kargoSirketiList;

            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int kargoSirketiId, string Tc, string Ad, string Soyad, string Tel)
        {
            Models.Kargocu _kargocu = new Models.Kargocu();
            _kargocu.Ad = Ad;
            _kargocu.Soyad = Soyad;
            _kargocu.TcNo = Tc;
            _kargocu.TelNo = Tel;
            _kargocu.KargoSirketiId = kargoSirketiId;
            db.Kargocu.Add(_kargocu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Update(int Id)
        {
            var kargocu = db.Kargocu.Single(x => x.Id == Id);
            return View(kargocu);
        }
        [HttpPost]
        public ActionResult Update(Models.Kargocu kargocu)
        {
            var _kargocu = db.Kargocu.Single(x => x.Id == kargocu.Id);
            _kargocu.Ad = kargocu.Ad;
            _kargocu.Soyad = kargocu.Soyad;
            _kargocu.TcNo = kargocu.TcNo;
            _kargocu.TelNo = kargocu.TelNo;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int Id)
        {
            db.Kargocu.Remove(db.Kargocu.Single(x => x.Id == Id));
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebApplication3/Views/Kargocu/Create.cshtml
@*@model WebApplication3.Models.Kargocu*@
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var kargoSirketiList = ViewData["KargoSirketi"] as List<WebApplication3.Models.KargoSirketi>;
}
<h2>Yeni Kargocu</h2>
@using (Html.BeginForm("Create", "Kargocu", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label for="Ad">Ad</label>
        <input class="form-control" name="Ad" />
        @*@Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })*@
    </div>
    <div class="form-group">
        <label for="Soyad">Soyad</label>
        <input class="form-control" name="Soyad" />
      @*  @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control" })*@
    </div>
    <div class="form-group">
        <label for="TcNo">TC NO</label>
        <input class="form-control" name="Tc" />
       @* @Html.TextBoxFor(x => x.TcNo, new { @class = "form-control" })*@
    </div>
    <div class="form-group">
        <label for="TelNo">Telefon</label>
        <input class="form-control" name="Tel" />
       @* @Html.TextBoxFor(x => x.TelNo, new { @class = "form-control", @type = "number" })*@
    </div>
    <div class="form-group">
        <label for="KargoSirketi">Kargo Şirketi</label>
        @Html.DropDownList("kargoSirketiId", new SelectList(kargoSirketiList.ToList(), "Id", "Ad"), "Kargo Şirketi Seçiniz", new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Ekle</button>
}

WebApplication3/Views/Kargocu/Delete.cshtml
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

WebApplication3/Views/Kargocu/Index.cshtml
@model IEnumerable<WebApplication3.Models.Kargocu>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Ad</th>
            <th scope="col">Soyad</th>
            <th scope="col">TC</th>
            <th scope="col">Tel</th>
            <th scope="col">KargoSirketiId</th>
            <th>
                <a href="@Url.Action("Create","Kargocu")" class="btn btn-primary">Yeni</a>
                @* <button type="button" class="btn btn-primary">Yeni</button>*@
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ToList())
        {
        <tr>
            <th scope="row">@item.Id</th>
            <td>@item.Ad</td>
            <td>@item.Soyad</td>
            <td>@item.TcNo</td>
            <td>@item.TelNo</td>
            <td>@item.KargoSirketiId</td>

            <td>
                <a href="@Url.Action("Update","Kargocu",new { @Id = item.Id})" class="btn btn-danger">Düzenle</a>
                <a href="@Url.Action("Delete","Kargocu",new { @Id = item.Id})" class="btn btn-danger">Sil</a>
            </td>

        </tr>
        }
    </tbody>
</table>

WebApplication3/Views/Kargocu/Update.cshtml
@model WebApplication3.Models.Kargocu
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Yeni Kargocu</h2>

@using (Html.BeginForm("Update", "Kargocu", FormMethod.Post))
{

    <div class="form-group">
        <label for="exampleInputEmail1">Id</label>
        @Html.TextBoxFor(x => x.Id, new { @class = "form-control", @readonly = "@readonly" })
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Kargocu Ad</label>
        @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Kargocu Soyad</label>
        @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Kargocu Tc NO</label>
        @Html.TextBoxFor(x => x.TcNo, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Kargocu Telefon</label>
        @Html.TextBoxFor(x => x.TelNo, new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-primary">Düzenle</button>
}